version: 0.2

phases:
  pre_build:
    commands:
      - npm install
  build:
    commands:
    - npm run build
  post_build:
    commands:
      - aws s3 cp --recursive ./ s3://devengineer.com.br
      - aws cloudfront create-invalidation --distribution-id EJXYSDLVRRENT --path /\*